### PR TITLE
Cleaning Rehab Model

### PR DESCRIPTION
**Pull request by SergeStinckwich**
Remove unecessary information ... All this info is manage by github now.

### CODE REVIEW

**Comment by SergeStinckwich** [comment]
Don't understand, why modelers will go through .st file? They will load their models from github.

**Comment by ElCep** [comment]
I can think of hundreds of reasons but some of them : 
* There's no Internet where we work.
* Users love their USB flash drives 
* there is a real 'enter cost' to git, which we no longer persevere with each other but which for non-modelers/non-computer scientists is very high.

**Comment by SergeStinckwich** [comment]
When you use CORMAS, you use a local git repository, so normally you have always access to that even if you have no connectivity. Why would people export their model as file if they have the real  model in their Pharo image?

**Comment by ElCep** [comment]
I understand your point of view, but what if someone sends you a .st model by email for example? Is there a way to see some times later how he is directly in your image ?

**Pull request merged**
