### PR TITLE
Removed + and - from protocol names

### PR DESCRIPTION
**Pull request by hernanmd**

### CODE REVIEW

**Comment by pierbo** [comment]
well, I think that, at least the prefixed protocols with + could be useful for the modelers, in order to help them find the methods they need, no?

**Comment by ElCep** [comment]
If I remember correctly we talked about using pragma instead of + and - . We can sort and filter on pragma in the interface no ?

**Comment by pierbo** [comment]
yes for sure, Pragmas should be much better (I never used them). But I wonder if, in addition, we could keep the + protocols...

**Comment by SergeStinckwich** [comment]
Keeping the + protocols does not make sense, because there will no relationships between pragmas and the methods in + protocols. What we can do later if to build a specific code browser or a plugin that shows this methods appropriately to the user.

**Review by SergeStinckwich — APPROVED** [review]

**Comment by pierbo** [comment]
OK ok !

**Pull request merged**
