### PR TITLE
Iss 470

### PR DESCRIPTION
**Pull request by hernanmd**
PR with multiple commits from MissABM

### CODE REVIEW

**Comment by SergeStinckwich** [comment]
Hi Hernan, I know that this not always possible to do, but can you breakdown a little bit more your PR and give more explanations both in the name of the PR and the comments, in order to ease the PR reviewers tasks.
I think this is important to have these peer reviews if we want to enhance the quality of the code at the end.

**Comment by SergeStinckwich** [comment]
CI is red with your PR.

**Comment by hernanmd** [comment]
Hi @SergeStinckwich I will try to do it for the next week, in the context of MissABM it is really difficult since I try to showcase CORMAS Pharo.

**Comment by SergeStinckwich** [comment]
No worries for this PR. I understand that sometimes this is not possible.

**Pull request closed without merging**
