### PR TITLE
add CMFishmanMooreRandomGenerator and fix CMAbstractModel>>getSimDescriptionText

### PR DESCRIPTION
**Pull request by tomooda**
add ``CMFishmanMooreRandomGenerator`` and fix ``CMAbstractModel>>getSimDescriptionText``

### CODE REVIEW

**Comment by SergeStinckwich** [comment]
We have already RNG in PolyMath (loaded by CORMAS baseline), we should be using these RNGs or move your RNG to PolyMath. What do you think about that?

**Comment by SergeStinckwich** [comment]
Ok sorry Tomo, I thought that PolyMath was already a dependency of CORMAS.

**Comment by tomooda** [comment]
There are many senders of the `seed:` to Cormas class, which makes difficult to use other RNG.
So, I'll send a pull request to PolyMath.

**Comment by tomooda** [comment]
Okay, I've sent a PR to PolyMath (https://github.com/PolyMathOrg/PolyMath/pull/177). I'll push a commit to use it after the PR is merged.

**Pull request merged**
