### PR TITLE
Cleaning in CMEntity

### PR DESCRIPTION
**Pull request by SergeStinckwich**

### CODE REVIEW

**Comment by SergeStinckwich** [comment]
Apparently ``colorOfNumber:`` does not reply the same thing if on MacOS or Linux.

**Comment by SergeStinckwich** [comment]
I dunno what happens here: green on my macOs, red on CI. @tomooda you have an idea?

**Comment by SergeStinckwich** [comment]
Ok I find the problem. New registered colors can be added by applications. This is not a fixed list.

**Comment by tomooda** [comment]
@SergeStinckwich I think you should define `colorNames` in `CMEntity class` so that it does not depend on the Color class.
```
colorNames
    | colorSpecs |
    colorSpecs := Color defaultColors, Color defaultColors2, Color defaultColors3, Color defaultColors4.
    ^ Array streamContents: [:stream | 1 to: cs size by: 4 do: [ :i | stream nextPut: (colorSpecs at: i) ]]
```

**Comment by SergeStinckwich** [comment]
Yes thank you @tomooda I will do that.

**Pull request merged**
