### PR TITLE
Remove methods in CMSpatialEntity

### PR DESCRIPTION
**Pull request by SergeStinckwich**

### CODE REVIEW

**Comment by cdrick65** [comment]
unused but won't be used in missing ports parts ?

**Comment by SergeStinckwich** [comment]
Confirmed to be unused in any models by @pierbo

**Comment by pierbo** [comment]
I would suggest to delete the following classes: CMGroup, CMGroupLocation, CMGroupComm and CMGroupCommLocation.

**Comment by SergeStinckwich** [comment]
Ok Pierre, I add you request to this issue: https://github.com/cormas/cormas/issues/111 so we keep track of it.

**Pull request closed without merging**
