### PR TITLE
CormasModelTest reconstructed with mock classes for testing

### PR DESCRIPTION
**Pull request by tomooda**
Add tests on the functionality of CormasModel that was done through testing on Conway, ECEC and FireAutomata.
Created mock classes CormasModelForTest and CMCellForTest as a mock to implement test code.

### CODE REVIEW

**Comment by ElCep** [comment]
the travis-ci doesn't work with this PR. But the problem come from the appel test ... @SergeStinckwich I see you've added apple tests. Are there any subtleties to those tests?

**Comment by tomooda** [comment]
Yes, the both jobs have failed by SecureTransport error. I suffer the same error in other projects which load many libraries via github repositories. Restarting the failed jobs often solves the problem.

**Comment by ElCep** [comment]
So we can merge and see later if something is wrong? I have no problem with is unorthodox way of use git :smile:

**Comment by ElCep** [comment]
all builds was green it was easier :+1:

**Pull request merged**
