### PR TITLE
CMEntity class>>shortName and related fixes

### PR DESCRIPTION
**Pull request by tomooda**
This simplifies the getters/setters/instVars names automatically generated in CMAbstractModel classes, which requires many fixes on the existing models. Tests included.

### CODE REVIEW

**Comment by tomooda** [comment]
Tests fail in Pharo 7. Do we still need to support Pharo 7?

**Comment by SergeStinckwich** [comment]
We should remove Pharo 7.0 and only focus on Pharo 8.0. This is already a lot of work.

**Comment by SergeStinckwich** [comment]
Apparently tests are failing both in Pharo 7.0 and 8.0

**Comment by tomooda** [comment]
Interesting. It was green when I checked the travis result. It seems that Pharo's file server is down, and we should wait until it will come back online.

**Comment by tomooda** [comment]
Hmm. Travis is still red on Pharo 8, and my installation on mac passes all tests. What's wrong?

**Comment by tomooda** [comment]
all green!

**Comment by SergeStinckwich** [comment]
Great job !

**Pull request merged**
